### ISSUE TITLE
Unable to exit from Onedrive Login Page 

### ISSUE THREAD

**Issue by reddykrishnaspan** [OneDrive/onedrive-picker-android#11]
Steps 
1. Launch Picker Sample
2. click on pick a file (sign into one drive page will open since i have not entered credentials when onedrive app installed from store)
3. click on back button from sign into one drive page
4.unable to navigate back to main page

**Comment by peternied** [comment]
Thanks for reporting, we are looking into this.

**Comment by reddykrishnaspan** [comment]
ok , thank you

**Comment by hanselip** [comment]
Hi @reddykrishnaspan, the bug has been fixed and will ship with the next release of OneDrive. Thanks for reporting!

**Comment by reddykrishnaspan** [comment]
Hi @hanselip  Thanks for the information

**Comment by hanselip** [comment]
Fix has shipped and is available in the latest OneDrive app (version 4.0.4)
