### ISSUE TITLE
Business filepicker

### ISSUE THREAD

**Issue by SlagbrandFrontwalker** [OneDrive/onedrive-picker-android#12]
The Onedrive app crashes when im trying to use the filepicker for business. Works great on personal. Im using linktyp.downloadlink and isnt the sdk suppose to support that for business?

**Comment by SlagbrandFrontwalker** [comment]
Anyone with similar problem? When I'm changing account to business in the picker or is only signed jn with business in overdrive the onedrive app crashes. Can't seem to find the issue in the log!

**Comment by peternied** [comment]
@SlagbrandFrontwalker Sorry I missed this issue last week.   It should work normally, but I'll see if I can track down what has happened in your case.

**Comment by SlagbrandFrontwalker** [comment]
Okay thanks, but this also happens If I run the picker sample from you. The picker crash as soon as I'm trying to intergrate with my business account! What could be wrong ?

**Comment by peternied** [comment]
This sounds like an issue within the integration within the OneDrive Android client, we have telemetry that should capture your crash so we can dig into it.  I'll circle back if we need more data, thanks.

**Comment by SlagbrandFrontwalker** [comment]
Thanks, do you have an idea of how much time it will take untill i get an answer. Kind of working with a deadline :)

**Comment by hanselip** [comment]
Hi @SlagbrandFrontwalker - we've identified the issue and the fix will ship with our next update. Target release date is in ~3 weeks but you could get the fix sooner if you are in our Beta program. Thank you for reporting the bug!

**Comment by hanselip** [comment]
Fix available in the latest OneDrive app version 4.0.4. Closing as resolved.
