### ISSUE TITLE
Onedrive crash when changing account

### ISSUE THREAD

**Issue by SlagbrandFrontwalker** [OneDrive/onedrive-picker-android#13]
I posted a issue before it was suppose to be fixed in the Onedrive 4.0.4 update last week. The porblem sitll exists.

The picker crashes when changing account to a business account. It gives the error message "did not get a file from picker" and then crashes.  The personal account works great but as soon as I interact with
the business account it crashes. This also happens when im running your pickerSample.

**Comment by hanselip** [comment]
Hi @SlagbrandFrontwalker - apologies, I was mistaken in the earlier thread about when the fix would ship. The fix isn't in 4.0.4 but will go out with the next release (4.1) which should be available in the next 1-2 weeks.

**Comment by hanselip** [comment]
4.1 has shipped and rolled out fully - please let us know if you're still hitting issues. Thanks!
