### ISSUE TITLE
PickerSample on real device (API 23) doesn't save files locally

### ISSUE THREAD

**Issue by SewDevks** [OneDrive/onedrive-picker-android#15]
after select a file save button starts download, download finishes successfully but there's no file on device storage.

**Comment by peternied** [comment]
The saver allows an application to save a file on OneDrive.  Within the saver sample application, a file is generated and then uploaded to OneDrive. If you check OneDrive the new file should be created there, not on the local device.

**Comment by SewDevks** [comment]
I think that's not the answer to my question/problem.
PickerSample allows user to select a file stored on OneDrive and download it to save it locally on the device. But used Download Manager doesn't save the content of the file.
