### ISSUE TITLE
upload file will fail above android 6.0 when don't grant "Storage" permission

### ISSUE THREAD

**Issue by yanbli** [OneDrive/onedrive-picker-android#16]
I am using the android 6.0 device. when I upload a file via Pick SDK, it will show the following error. Actually when I go to onedrive page, that file has been created. It is empty file.

But I grant the "Storage" permission, it can work very well.

But when I directly upload files via OneDrive app, it can success.
Why does it need to storage permission to upload for Pick SDK? Can you fix this issue?

![5f612d86-cd9f-11e5-89cc-f7c36de442e6](https://cloud.githubusercontent.com/assets/13902584/15496879/5e199c40-21ca-11e6-91ec-e6e245115ba8.png)

**Comment by hanselip** [comment]
Hi yanbli - so the OneDrive app in general needs Storage permissions (for writing temp files, etc.), so I've made a change to ensure we prompt for those permissions on this screen when the upload button is tapped. This should hopefully reduce confusion around the 'Generic Error' seen today.

**Comment by peternied** [comment]
I believe this issue has been fixed for a while now, please reopen if this is still a problem with the latest version of the OneDrive client for Android.
